# Generated by Django 5.1 on 2025-09-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_List', '0002_alter_ride_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id_ride',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ride_event',
            name='id_ride_event',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
