# Generated by Django 5.1 on 2025-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_List', '0003_alter_ride_id_ride_alter_ride_event_id_ride_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(null=True),
        ),
    ]
