# Generated by Django 5.1 on 2025-09-04 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_List', '0004_alter_ride_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='id_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_ride', to='Ride_List.user'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
